name: Build and Test Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
              echo "Simulating build process..."
              # In a real scenario, this would be `npm install` and `npm run build`
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-app-build
          path: . # Assuming your build artifacts are in the root for this example

  test:
    runs-on: ubuntu-latest
    needs: build # This job will only run after the 'build' job completes successfully
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-app-build
      - name: Run tests
        run: |
              echo "Simulating test process..."
              # In a real scenario, this would be `npm test`
            
