name: Manual Trigger Info

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Trigger Info
        run: |
              echo "Workflow triggered by: ${{ github.event_name }}"
              echo "Ref: ${{ github.ref }}"
              echo "Actor: ${{ github.actor }}"
              echo "Repository: ${{ github.repository }}"
              echo "Commit SHA: ${{ github.sha }}"
